### ISSUE TITLE
tf 2.4?

### ISSUE THREAD

**Issue by bjarthur** [google-research/leaf-audio#7]
why `==` in requirements.txt and not `>=`?  does leaf-audio really not work with tf 2.4 and numpy 1.20?

```
numpy==1.18.2
tensorflow==2.3.1
tensorflow-gpu==2.3.1
```

**Comment by lienz** [comment]
Hi, this was necessary for compatibility with lingvo but now lingvo 0.9.0 handles newer versions of tensorflow, our latest commit makes Leaf compatible with tf 2.5.
